name: E2E Test

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Vitest browser mode
        run: |
          pnpm exec playwright install chromium --with-deps
          pnpm build:esm
          pnpm test:browser
